name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build DEX
      run: ./gradlew generateDexRelease
    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./lib/build/outputs/dex/release/classes.dex"
        name: "Release ${{ github.ref }}"
        body: "TEST\nAnother test\n\n[Hyperlink Test]()"